# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master

jobs:

- job: 'Test'
  pool:
    vmImage: 'Ubuntu-16.04'
  strategy:
    matrix:
      Python36:
        python.version: '3.6'
      Python37:
        python.version: '3.7'
    maxParallel: 2

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'

  - script: python -m pip install --upgrade pip && pip install -r build-requirements.txt
    displayName: 'Install dependencies'

  - script: |
      pip install pytest
      pytest test --doctest-modules --junitxml=junit/test-results.xml
    displayName: 'pytest'

  - task: PublishTestResults@2
    inputs:
      testResultsFiles: '**/test-results.xml'
      testRunTitle: 'Python $(python.version)'
    condition: succeededOrFailed()

- job: 'Publish'
  dependsOn: 'Test'
  pool:
    vmImage: 'Ubuntu-16.04'

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      architecture: 'x64'

  - script: python setup.py sdist
    displayName: 'Build sdist'

  - script: pip install twine
    displayName: Installing Twine

  - script: |
      ouput=$(twine upload dist/* --disable-progress-bar --skip-existing -u $(TwineUser) -p $(TwinePassword))
      echo "${output}"
      if $output | grep -q 'exist' ; then
        echo "Package uploaded successfully"
        exit 0
      else
        echo "Package version already uploaded. Bump the version."
        exit 1
      fi
    displayName: Uploading to PyOrg via Twine