# Generates a Python package if the code passes the test
# Create and test a Python code on multiple Python versions
# Uploads the package with a new version to Pypi.org

trigger:
  batch: true # Batch the changes if there are many commits in a short burst
  branches:
    include: # Only use the master branch
    - master
  paths:
    include: # Only includes the outsystems pipeline code as trigger
      - outsystems/*
    exclude: # Excludes everything else
      - /*

# Exclude pull requests
pr: none

jobs:
- job: 'Test'
  pool:
    vmImage: 'Ubuntu-16.04'
  strategy:
    matrix:
      Python36:
        python.version: '3.6'
      Python37:
        python.version: '3.7'
    maxParallel: 2

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'

  - script: python -m pip install --upgrade pip && pip install -r build-requirements.txt
    displayName: 'Install dependencies'

  - script: |
      pip install pytest
      pytest test --doctest-modules --junitxml=junit/test-results.xml
    displayName: 'pytest'

  - task: PublishTestResults@2
    inputs:
      testResultsFiles: '**/test-results.xml'
      testRunTitle: 'Python $(python.version)'
    condition: succeededOrFailed()

- job: 'Publish'
  dependsOn: 'Test'
  pool:
    vmImage: 'Ubuntu-16.04'

  steps:
  - checkout: self
    persistCredentials: true

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      architecture: 'x64'

  - script: |
      pip search outsystems-pipeline | grep outsystems-pipeline | grep -oE "\(.*?\)" | tr --delete "()" > VERSION
      if [ "$(ReleaseType)" == "major" ]; then
        python build/version_bumper.py
      else
        python build/version_bumper.py --$(ReleaseType)
      fi
      python setup.py sdist
    displayName: 'Build sdist'

  - script: pip install twine
    displayName: Installing Twine

  - script: twine upload dist/* --disable-progress-bar --skip-existing -u $(TwineUser) -p $(TwinePassword)
    displayName: Uploading to PyOrg via Twine