pipeline {
  agent any
  options { skipStagesAfterUnstable() }
  environment {
    // Artifacts Specific Variables
    ArtifactsFolder = "Artifacts"
    // LifeTime Specific Variables
    LifeTimeEnvironmentURL = "${params.LTUrl}"
    LifeTimeAPIVersion = "${params.LTApiVersion}"
    // Authentication Specific Variables
    AuthorizationToken = credentials('IntranetLifeTimeServiceAccountToken')
  }
  stages {
    stage('Install Python Dependencies and create Artifact directory') {
      steps {
        echo "Create Artifacts Folder"
        powershell "mkdir ${env.ArtifactsFolder}"
        // Only the virtual environment needs to be installed at the system level
        echo "Install Python Virtual environments"
        powershell 'pip install -q -I virtualenv'
        // Install the rest of the dependencies at the environment level and not the system level
        withPythonEnv('python') {
          echo "Install Python requirements"
          powershell 'pip install -q -I -r .\\cd_pipelines\\jenkins\\requirements.txt'
        }
      }
    }
    stage('Get Latest Applications and Environments from LifeTime') {
      steps {
        withPythonEnv('python') {
          echo 'Retrieving latest application tags from Development environment...'
          powershell "python .\\outsystems\\pipeline\\fetch_lifetime_data.py --artifacts \"${env.ArtifactsFolder}\" --lt_url \"${env.LifeTimeEnvironmentURL}\" --lt_token \"${env.AuthorizationToken}\" --lt_api_version \"${env.LifeTimeAPIVersion}\""
        }
      }
      post {
        always {
          dir ("${env.ArtifactsFolder}") {
            archiveArtifacts artifacts: "*.cache", onlyIfSuccessful: true
          }
        }
      }
    }
    stage('Deploy tags to Regression Environment') {
      environment {
        // Environment where the latest versions of the apps currently are
        SourceEnvironment = "${params.DevEnv}"
        // Environment where you want to publish the apps
        TargetEnvironment = "${params.RegEnv}"
        // Apps you want to deploy
        ApplicationsToDeploy = "${params.AppScope},${params.AppWithTests}"
      }
      steps {
        withPythonEnv('python') {
          echo 'Deploying latest application tags to Regression...'
          powershell "python .\\outsystems\\pipeline\\deploy_latest_tags_to_target_env.py --artifacts \"${env.ArtifactsFolder}\" --lt_url \"${env.LifeTimeEnvironmentURL}\" --lt_token \"${env.AuthorizationToken}\" --lt_api_version \"${env.LifeTimeAPIVersion}\" --source_env \"${env.SourceEnvironment}\" --destination_env \"${env.TargetEnvironment}\" --app_list \"${env.ApplicationsToDeploy}\""
        } 
      }
      post {
        always {
          dir ("${env.ArtifactsFolder}") {
            archiveArtifacts artifacts: "*_data/*.cache", onlyIfSuccessful: true
          }
        }
        failure {
          dir ("${env.ArtifactsFolder}") {
            archiveArtifacts artifacts: "DeploymentConflicts"
          }
        }
      }
    }
    stage('Run Regression tests on the Regression Environment') {
      environment {
        // BDD Framework Specific Variables
        BDDUrl = "${params.BddUrl}"
        // CICD Probe Specific Variables
        CICDProbeUrl = "${params.ProbeUrl}"
        // Apps to run tests on
        ApplicationsToTest = "${params.AppScope},${params.AppWithTests}"
        // Slack Specific Variables
        SlackHook = credentials('slack-hook')
        SlackChannel = "${params.SlackChannel}"
      }
      steps {
        withPythonEnv('python') {
          echo 'Generating URLs for BDD testing...'
          powershell "python .\\outsystems\\pipeline\\generate_unit_testing_assembly.py --artifacts \"${env.ArtifactsFolder}\" --app_list \"${env.ApplicationsToTest}\" --cicd_probe_env \"${env.CICDProbeUrl}\" --bdd_framework_env \"${env.BDDUrl}\""
          echo "Testing the URLs and generating the JUnit results XML..."
          powershell(script: "python .\\outsystems\\pipeline\\evaluate_test_results.py --artifacts \"${env.ArtifactsFolder}\"", returnStatus: true)
        }
      }
      post {
        always {
          withPythonEnv('python') {
            echo "Publishing JUnit test results..."
            junit(testResults: "${env.ArtifactsFolder}\\junit-result.xml", allowEmptyResults: true)
            echo "Sending notifcations to slack..."
            powershell "python .\\custom_pipeline\\slack\\send_test_results_to_slack.py --artifacts \"${env.ArtifactsFolder}\" --slack_hook \"${env.SlackHook}\" --slack_channel \"${env.SlackChannel}\" --job_name \"${env.JOB_NAME}\" --job_dashboard_url \"${env.RUN_DISPLAY_URL}\""
          }
          dir ("${env.ArtifactsFolder}") {
            archiveArtifacts artifacts: "*_data/*.cache", onlyIfSuccessful: true
          }
        }
      }
    }
    stage('Deploy to Quality Assurance Environment') {
      environment {
        // Environment where the latest versions of the apps currently are
        SourceEnvironment = "${params.RegEnv}"
        // Environment where you want to publish the apps
        TargetEnvironment = "${params.QAEnv}"
        // Apps you want to deploy
        ApplicationsToDeploy = "${params.AppScope}"
      }
      steps {
        // Wrap the confirm in a timeout to avoid hanging Jenkins forever
        timeout(time:1, unit:'DAYS') {
          input 'Deploy changes to Acceptance?'
        }
        withPythonEnv('python') {
          echo 'Deploying latest application tags to Acceptance...'
          powershell "python .\\outsystems\\pipeline\\deploy_latest_tags_to_target_env.py --artifacts \"${env.ArtifactsFolder}\" --lt_url \"${env.LifeTimeEnvironmentURL}\" --lt_token \"${env.AuthorizationToken}\" --lt_api_version \"${env.LifeTimeAPIVersion}\" --source_env \"${env.SourceEnvironment}\" --destination_env \"${env.TargetEnvironment}\" --app_list \"${env.ApplicationsToDeploy}\""
        }
      }
      post {
        always {
          dir ("${env.ArtifactsFolder}") {
            archiveArtifacts artifacts: "*_data/*.cache", onlyIfSuccessful: true
          }
        }
        failure {
          dir ("${env.ArtifactsFolder}") {
            archiveArtifacts artifacts: "DeploymentConflicts"
          }
        }
      }
    }
    stage('Confirm push to Pre-Production and Production') {
      steps {
        // Wrap the confirm in a timeout to avoid hanging Jenkins forever
        timeout(time:1, unit:'DAYS') {
          input 'Accept changes and deploy to Pre- and Production?'
        }
      }
    }
    stage('Deploy to Pre-Production Environment') {
      environment {
        // Environment where the latest versions of the apps currently are
        SourceEnvironment = "${params.QAEnv}"
        // Environment where you want to publish the apps
        TargetEnvironment = "${params.PpEnv}"
        // Apps you want to deploy
        ApplicationsToDeploy = "${params.AppScope}"
      }
      steps {
        withPythonEnv('python') {
          echo 'Deploying latest application tags to Pre-Production...'
          powershell "python .\\outsystems\\pipeline\\deploy_latest_tags_to_target_env.py --artifacts \"${env.ArtifactsFolder}\" --lt_url \"${env.LifeTimeEnvironmentURL}\" --lt_token \"${env.AuthorizationToken}\" --lt_api_version \"${env.LifeTimeAPIVersion}\" --source_env \"${env.SourceEnvironment}\" --destination_env \"${env.TargetEnvironment}\" --app_list \"${env.ApplicationsToDeploy}\""
        }
      }
      post {
        always {
          dir ("${env.ArtifactsFolder}") {
            archiveArtifacts artifacts: "*_data/*.cache", onlyIfSuccessful: true
          }
        }
        failure {
          dir ("${env.ArtifactsFolder}") {
            archiveArtifacts artifacts: "DeploymentConflicts"
          }
        }
      }
    }
    stage('Deploy to Production Environment') {
      environment {
        // Environment where the latest versions of the apps currently are
        SourceEnvironment = "${params.PpEnv}"
        // Environment where you want to publish the apps
        TargetEnvironment = "${params.PrdEnv}"
        // Apps you want to deploy
        ApplicationsToDeploy = "${params.AppScope}"
      }
      steps {
        sleep 60 // TODO: Replace by polling script that checks whenever the sync in PRE is finished
        withPythonEnv('python') {
          echo 'Deploying latest application tags to Production...'
          powershell "python .\\outsystems\\pipeline\\deploy_latest_tags_to_target_env.py --artifacts \"${env.ArtifactsFolder}\" --lt_url \"${env.LifeTimeEnvironmentURL}\" --lt_token \"${env.AuthorizationToken}\" --lt_api_version \"${env.LifeTimeAPIVersion}\" --source_env \"${env.SourceEnvironment}\" --destination_env \"${env.TargetEnvironment}\" --app_list \"${env.ApplicationsToDeploy}\""
        }
      }
      post {
        always {
          dir ("${env.ArtifactsFolder}") {
            archiveArtifacts artifacts: "*_data/*.cache", onlyIfSuccessful: true
          }
        }
        failure {
          dir ("${env.ArtifactsFolder}") {
            archiveArtifacts artifacts: "DeploymentConflicts"
          }
        }
      }
    }
  }
  post {
    always { 
      echo 'Deleting artifacts folder content...'
      dir ("${env.ArtifactsFolder}") {
        deleteDir()
      }
    }
  }
}
