# ******************************************************************
# Template: RegressionTestingJob-AzureAgent
# ******************************************************************
# TBD
# ******************************************************************

# ******************************************************************
# Declare jobs
# ******************************************************************
jobs:

# ******************************************************************
# Job: BDD Regression Testing 
# ******************************************************************
# Run list of BDD test jobs and publish results to the pipeline 
# ******************************************************************
- job: regression_testing_bdd
  displayName: Regression Testing (BDD)
  dependsOn: lifetime_deployment
  steps:
  - download: current
  - template: ../tasks/InstallPythonPackage.yaml # Install python package

  # ******************************************************************
  # Step: Get App List from Manifest
  # ******************************************************************
  # Gets a comma-separated list of the application names
  # found on the Trigger Manifest artifact
  # ******************************************************************
  - script: |
      AppList=$(cat "$(Pipeline.Workspace)/$(Manifest.Folder)/$(Manifest.File)" | jq -c '.ApplicationVersions | map(.ApplicationName) | join(",")')
      echo "##vso[task.setvariable variable=AppList;isOutput=true]$AppList"
    displayName: 'Get App List from Manifest'
    name: get_app_list

  # ******************************************************************
  # Step: Generate URL endpoints for BDD test suites 
  # ******************************************************************
  # Generate a list of URL endpoints to query the BDD framework
  # ******************************************************************
  - script: >
      python -m outsystems.pipeline.generate_unit_testing_assembly
      --artifacts "$(Artifacts.Folder)" 
      --app_list $(get_app_list.AppList)
      --cicd_probe_env "$(CICDProbe.EnvironmentURL)"
      --bdd_framework_env "$(BDDFramework.EnvironmentURL)"
    displayName: 'Generate URL endpoints for BDD test suites'

  # ******************************************************************
  # Step: Run BDD test suites and generate JUnit test report
  # ******************************************************************
  # Calls each BDD test URL and store the results in JUnit format
  # ******************************************************************
  - script: |
      python -m outsystems.pipeline.evaluate_test_results --artifacts "$(Artifacts.Folder)"
      exit 0
    displayName: 'Run BDD test suites and generate JUnit test report'
  
  # ******************************************************************
  # Step: Publish test results
  # ******************************************************************
  # Publish results from the JUnit test result file
  # ******************************************************************
  - task: PublishTestResults@2
    inputs:
      testRunTitle: 'BDD Tests'
      testResultsFormat: 'JUnit'
      testResultsFiles: 'junit-result.xml' 
      searchFolder: '$(Artifacts.Folder)'
      mergeTestResults: true
      failTaskOnFailedTests: true    
    displayName: 'Publish test results'
