# This is a basic workflow that is manually triggered to create a python virtual environment

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      env_name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Runner Python virtual env name'
        # Default value if no value is explicitly provided
        default: 'default_outsystems_env'
        # Input has to be provided for the workflow to run
        required: true

jobs:
  
  install_dependencies:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        path: main
    - name: Send greeting
      run: ./examples/Linux/install_dependencies.sh -e ${{ github.event.inputs.name }} -a/tmp/artifacts
